export enum  Route {
    MAIN_NAVIGATOR = 'MAIN_NAVIGATORr',
    AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
    HOME_SCREEN = 'HOME_SCREEN',
    REGISTER_SCREEN = 'REGISTER_SCREEN',
    LOGIN_SCREEN = 'LOGIN_SCREEN',
    WELCOME_SCREEN = 'WELCOME_SCREEN',
    FORGET_PASSWORD_SCREEN = 'FORGET_PASSWORD_SCREEN',
    CAMERA_SCREEN = 'CAMERA_SCREEN',
 }